version: '3.9'

services:
  db_master:
    image: postgres:latest
    environment:
      POSTGRES_USER: newsfeed
      POSTGRES_PASSWORD: newsfeed
    volumes:
      - ./.data/master/data:/var/lib/postgresql/data
      - ./.data/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  db_slave:
    image: postgres:latest
    environment:
      POSTGRES_USER: newsfeed_slave
      POSTGRES_PASSWORD: newsfeed_slave
      POSTGRES_MASTER_HOST: master
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - ./.data/slave/data:/var/lib/postgresql/data
    restart: always

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge