###
# Create doc with id 34. Sending without 34 creates random index.
POST localhost:9200/my_index/_doc/13
Content-Type: application/json

{
  "short": "Some about Leopard 1 and his old but gold gun",
  "label": "medicine"
}

###
GET localhost:9200/my_index/_doc/34

###
# Replaces entite JSON body.
PUT localhost:9200/my_index/_doc/32
Content-Type: application/json

{
  "filter": "2A6"
}

###
# Updating data.
POST localhost:9200/my_index/_update/34
Content-Type: application/json

{
  "doc": {
    "page": 34333
  }
}