###
# Mapping for index
PUT localhost:9200/my_index/_mapping
Content-Type: application/json

{
  "properties": {
    "short":   { "type": "text" },
    "label": {"type": "keyword"}
  }
}

###
# GET Mapping for index
GET localhost:9200/my_index/_mapping